live_config_reload = true

[bell]
command = "None"
duration = 0

[colors]
draw_bold_text_with_bright_colors = false
[colors.primary]
background = "#181818"

[cursor]
unfocused_hollow = true
vi_mode_style = "Beam"

[cursor.style]
shape = "Block"

[env]
TERM = "alacritty"

[font]
builtin_box_drawing = true
size = 16.0

[font.normal]
family = "Mononoki Nerd Font"

[hints]
alphabet = "asdfjklghcmie"

[[keyboard.bindings]]
chars = "\u001B[72;5u"
key = "H"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[74;5u"
key = "J"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[75;5u"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[76;5u"
key = "L"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[shell]
program = "/usr/bin/zsh"

[window]
decorations = "none"
dynamic_title = false
opacity = 0.85
startup_mode = "Maximized"
title = "Alacritty"

[window.padding]
x = 2
y = 2
