[general]
live_config_reload = true
import = ["~/.config/alacritty/theme.toml"]

[window]
decorations = "None"
opacity = 0.9
startup_mode = "Maximized"
title = "Alacritty"
dynamic_title = false

[font]
normal = { family = "Mononoki Nerd Font", style = "regular" }
size = 15

[cursor]
style = { shape = "Block", blinking = "Off" }
vi_mode_style = { shape = "Beam", blinking = "Off" }

[mouse]
hide_when_typing = true

[hints]
alphabet = "asenrtiucodhv"

[[hints.enabled]]
command = "xdg-open" # On Linux/BSD
# command = "open" # On macOS
# command = { program = "cmd", args = [ "/c", "start", "" ] } # On Windows
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "o", mods = "Alt" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://|obsidian://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`\\\\]+"

[keyboard]
bindings = [
  { key = "+", mods = "Alt", action = "IncreaseFontSize" },
  { key = "-", mods = "Alt", action = "DecreaseFontSize" },
  { key = "/", mods = "Alt", action = "ResetFontSize" },
  { key = "n", mods = "Alt|Shift", action = "CreateNewWindow" },
]

[window.padding]
x = 2
y = 2
