#!/bin/sh
# Date: 2021/10/06
# Description: Changes the folders.cfg's line for 42 faster

folders_cfg_path="$HOME/.config/zsh/foldersrc"

arg="$1"
relative_pwd=$(echo "$PWD" | sed "s|$HOME|~|")

OS=$(getos)
if [ "$OS" = "OSX" ]; then
	sed "s|^42.*|42			$relative_pwd/$arg|" "$folders_cfg_path" > tmp_42folder.cfg
	mv tmp_42folder.cfg "$folders_cfg_path"
elif [ "$OS" = "LINUX" ]; then
	sed -i "s|^42.*|42			$relative_pwd/$arg|" "$folders_cfg_path"
fi

echo "New 42 shortcut is $relative_pwd/$arg"
echo "Run source ~/.zshrc to update"
