#!/bin/sh
# Date: 2025/06/25
# Description: Lets the user select an Ollama model and runs it.

SELECTED_MODEL=$(ollama list | cut -d ' ' -f 1 | tail -n +2 | fzf --prompt "Select an Ollama model: ")

ollama run "$SELECTED_MODEL" --hidethinking
