#!/bin/bash
#  _____ _                           ______        ____        ____        __ 
# |_   _| |__   ___ _ __ ___   ___  / ___\ \      / /\ \      / /\ \      / / 
#   | | | '_ \ / _ \ '_ ` _ \ / _ \ \___ \\ \ /\ / /  \ \ /\ / /  \ \ /\ / /  
#   | | | | | |  __/ | | | | |  __/  ___) |\ V  V /    \ V  V /    \ V  V /   
#   |_| |_| |_|\___|_| |_| |_|\___| |____/  \_/\_/      \_/\_/      \_/\_/    
#                                                                             
#  
# by Stephan Raabe (2023) 
# ----------------------------------------------------- 

# ----------------------------------------------------- 
# Select random wallpaper
# ----------------------------------------------------- 
wallpaper=`ls "$HOME/Pictures/wallpapers" | sort -R | tail -1`

"$HOME/.local/bin/swww" img "$HOME/Pictures/wallpapers/$wallpaper" --transition-step 20 --transition-fps=20 2> /tmp/swww-pb

if [ -s /tmp/swww-pb ]; then
	error=`cat /tmp/swww-pb`
	notify-send "swww had a problem" "$error"
fi
