#!/bin/sh
# Date: 2025/03/05
# Description: A script to help me find what settings I'm editing so I can reproduce on other desktops.

# Write all the settings to a file
gsettings list-recursively > /tmp/gsettings_before.txt

# Wait for the user to make changes
read -p "Press enter when you're done making changes"

# Write all the settings to a file
gsettings list-recursively > /tmp/gsettings_after.txt

# Diff the two files
diff /tmp/gsettings_before.txt /tmp/gsettings_after.txt
