#!/bin/sh
# Date: 2024/05/27
# Description: Configure git user

emails=("paul.lv.ohl@gmail.com" "paul.ohl@bedrockstreaming.com")
userName="Paul Ohl"

selectedEmail=$(echo "${emails[@]}" | tr ' ' '\n' | fzf --algo=v1 --border --border-label="╢ Which address to use? ╟" --color=label:italic:black)
if [ -z "$selectedEmail" ]; then
    echo "No email selected"
    exit 1
fi

git config user.email "$selectedEmail"
git config user.name "$userName"

