#!/bin/sh
# Date: 2024/05/27
# Description: Configure git user

emails=("paul.lv.ohl@gmail.com" "other@email.com")
userName="Paul Ohl"

# selectedEmail=$(echo "${emails[@]}" | tr ' ' '\n' | fzf --algo=v1 --border --border-label="╢ Which address to use? ╟" --color=label:italic:black)
selectedEmail="paul.lv.ohl@gmail.com"
if [ -z "$selectedEmail" ]; then
    echo "No email selected"
else
    git config user.email "$selectedEmail"
    git config user.name "$userName"
fi
