#!/bin/sh
# Date: 2022/05/10
# Description: Git Fetch All, fetches all branches from all remotes

git branch -r | grep -v '\->' | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g" | \
	while read remote; do
		git branch --track "${remote#origin/}" "$remote"
	done

git fetch --all
git pull --all
