#!/bin/sh
# Date: 2021/05/07
# Description: Creates a project for c or c++ with a Makefile, a directory
# structure and a .gitignore

SCRIPT_FILES="$HOME/.config/custom_scripts/mkproject_files"

if ! [ "$1" = "" ]; then
	mkdir "$1" || exit 1
	cd "$1" || exit 1
fi

if ! [ -d 'srcs' ]; then
	mkdir srcs/ || exit 1
fi

if ! [ -d 'incs' ]; then
	mkdir incs/ || exit 1
fi

if [ -e ".gitignore" ]; then
	echo "There is already a .gitignore present, appending at the end."
	{ echo ""; echo "# Added by mkproject script:"; } >> .gitignore
	cat "$SCRIPT_FILES/gitignore" >> .gitignore
else
	cp "$SCRIPT_FILES/gitignore" .gitignore
fi

if [ -e 'Makefile' ]; then
	printf 'There is already a Makefile present, do you want to replace it? [y/n]: '
	read -r user_input
	user_input=$(echo "$user_input" | tr '[:upper:]' '[:lower:]')
	if [ "$user_input" = 'y' ]; then
		cp "$SCRIPT_FILES/Makefile" Makefile
	fi
else
	cp "$SCRIPT_FILES/Makefile" Makefile
fi

echo "Done ✓"

if [ "$EDITOR" = "" ]; then
	vim Makefile
else
	$EDITOR Makefile
fi
