#!/bin/bash
# Date: 2022/07/31
# Description: Simple Bluetooth Manager for Macos

if [ "$(blueutil --power)" = "0" ]; then
	turn_bt_on=$(printf "Turn Bluetooth on\nDo nothing" | choose -i)
	if [ "$turn_bt_on" = "0" ]; then
		blueutil --power 1
	else
		exit 0
	fi
fi

paired_devices=$(blueutil --paired)
paired_devices=$(echo "$paired_devices" | sed 's/ (.*)//' | sed 's/, /\t/g')

echo "$paired_devices" | \
	awk -F \t '
		{ print $0 }
		{ if ($2 == "connected") { print "connected" } else print "no" }
	'
		# { if ($3 != "connected") print "HI" }

exit 0

echo "$paired_devices" | choose
disconnected="🔴"
connected="🟢"
