#!/bin/sh
# Date: 2024/06/18

apps="Slack Telegram Teams Mail"

selected_app=$(echo "$apps" | tr ' ' '\n' | wofi --dmenu --insensitive --width 400 --lines 5 --prompt "Select an app")

case $selected_app in
  "Slack")
    flatpak run com.slack.Slack
    ;;
  "Telegram")
    flatpak run org.telegram.desktop
    ;;
  "Teams")
    flatpak run com.github.IsmaelMartinez.teams_for_linux
    ;;
  *)
    ;;
esac
