#!/bin/sh
#     ::::::::   ::::::  :::   ::: :::
#    :+:   :+: :+:  :+: :+:   :+: :+:  Paul OHL
#   +#++++#+  +#+  +:+ +#++:+#++ +#+
#  #+#       #+#  #+# #+#   #+# #+#
# ###        ######  ###   ### #######
#
# Created: 2022/03/28 12:36:04
# Description: updates or installs the programs I usually use
#

failure_exit() {
	echo "Failure, exiting"
	exit 1
}

update_hosts_file() {
	echo "hosts file"
	hosts_version_file="$HOME/.local/local_config/hosts_version" 
	latest_version=$(curl -s "https://github.com/StevenBlack/hosts/releases/latest" | sed 's/.*tag\///' | sed 's/\".*//')
	local_version=$(cat "$hosts_version_file" 2> /dev/null)
	if [ "$local_version" = "$latest_version" ]; then
		echo "Up to date!"
		return 0
	fi
	sudo cp /etc/hosts /etc/hosts_backup || return 1
	curl "https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts" | sudo tee /etc/hosts > /dev/null || return 1
	printf "0.0.0.0	www.youtube.com\n0.0.0.0 9gag.com\n" | sudo tee -a /etc/hosts > /dev/null || return 1
	echo "$latest_version" > "$hosts_version_file"
	return 0
}

update_zsh_syntax_highlighting() {
	echo "zsh_syntax_highlighting"
	zsh_directory="$HOME/.local/git/zsh-syntax-highlighting"
	mkdir -p "$zsh_directory"
	if ! [ -e "$zsh_directory/zsh-syntax-highlighting.zsh" ]; then
		git clone --depth 1 --recurse-submodules --shallow-submodules https://github.com/zsh-users/zsh-syntax-highlighting.git "$zsh_directory"
	else
		cd "$zsh_directory" || return 1
		git pull
		cd - > /dev/null || return 1
	fi
	return 0
}

update_hosts_file || failure_exit
update_zsh_syntax_highlighting || failure_exit
brew update && brew upgrade && brew upgrade --cask && brew cleanup
nvim -c 'call Updatr()|qa'
