#!/bin/sh
# Date: 2022/03/12
# Description: Encrypt/Decrypt folders/files, source this file to access the
#			   functions

encrypt() {
  tar --create --file - --gzip -- "$@" | \
  openssl aes-256-cbc -salt -out out.enc
}

decrypt() {
  openssl aes-256-cbc -d -salt -in "$1" | \
  tar -v --extract --gzip --file -
}
